### ISSUE TITLE
Exporting to GoogleMaps models

### ISSUE THREAD

**Issue by ErunamoJAZZ** [cocoahero/android-geojson#2]
Hi.

I think a very useful use case is able to move from GeoJSON structures GoogleMaps v2.

Something like `myPoint.toGoogleMaps()` -> return a type Marker.

https://developer.android.com/reference/com/google/android/gms/maps/model/package-summary.html

**Comment by cocoahero** [comment]
While I can see the usefulness of such a feature, I believe such conversion is out of scope of this library, and would introduce a dependency on the Google Maps SDK.

@VanitySoft please file a separate issue if you are still having a problem.
